### PR TITLE
Document attributes, signals

### PR DESCRIPTION
**Pull request by nyalldawson**
Requires https://github.com/qgis/QGIS/pull/58372

Fixes https://github.com/qgis/pyqgis-api-docs-builder/issues/27

### CODE REVIEW

**Review by 3nids — APPROVED** [review]
nice!

**Comment by 3nids** [comment]
@nyalldawson not sure if that's part of this, but it might be better to drop or alter the signature?

image

**Comment by DelazJ** [comment]
Should it not be fixed after https://github.com/qgis/QGIS/pull/58372?

**Comment by nyalldawson** [comment]
@DelazJ @3nids yes, we need the main repo change committed too

**Pull request merged**
